<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>登录</title>
    <!-- Bootstrap -->
    <link href="/project/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="/project/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="/project/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- Animate.css -->
    <link href="/project/vendors/animate.css/animate.min.css" rel="stylesheet">
    <!-- Custom Theme Style -->
    <link href="/project/build/css/custom.min.css" rel="stylesheet">
  </head>
  <body class="login">
    <div>
        <a class="hiddenanchor" id="signup"></a>
        <a class="hiddenanchor" id="forgot"></a>
        <a class="hiddenanchor" id="signin"></a>
      <div class="login_wrapper">
        <div class="animate form login_form">
          <section class="login_content">
            <form>
              <h1>登 录</h1>
              <div>
                <input id="loginname" type="text" class="form-control" placeholder="用户名" required="" />
              </div>
              <div>
                <input id="loginpassword" type="password" class="form-control" placeholder="密 码" required="" />
              </div>
              <div>
                <a id="enterbtn" class="btn btn-default submit" href="javascript:void(0);" onclick="userlogin()">确 认</a>
                <a class="reset_pass" href="#forgot">忘记密码?</a>
              </div>
              <div class="clearfix"></div>
              <div class="separator">
                  <a href="#signup" class="to_register"> 创建账号 </a>
                <div class="clearfix"></div>
                <br />
                <div>
                  <p>©2018 All Rights Reserved.</p>
                </div>
              </div>
            </form>
          </section>
        </div>
          <div id="forgot" class="animate form forgot_form">
              <section class="login_content">
                  <form>
                      <div>
                          <input id="loginname_try" type="text" class="form-control" placeholder="输入用户名，系统会发送验证码给您" required="" />
                      </div>
                      <div>
                          <input id="code" type="text" class="form-control" placeholder="输入收到的验证码" required="" />
                      </div>
                      <a class="btn btn-default submit" href="javascript:void(0);" onclick="sendcode()">发送验证码</a>
                      <a class="btn btn-default submit" href="javascript:void(0);" onclick="login()">登录</a>
                  </form>
                  <div class="separator">
                      <p class="change_link">账号想起来了？
                          <a href="#signin" class="to_register"> 登录 </a>
                      </p>
                      <div class="clearfix"></div>
                      <br />
                      <div>

              </section>
          </div>
        <div id="register" class="animate form registration_form">
          <section class="login_content">
            <form>
              <h1>创建账号</h1>
              <div>
                <input id="username" type="text" class="form-control" style="border-color: #F44336" placeholder="用户名（必填）：登录网站的用户名" />
              </div>
                <div>
                <input  id="password" type="password" class="form-control" style="border-color: #F44336" placeholder="密码（必填）：登录网站的密码"  />
              </div>
               <div>
                <input  id="password2" type="password" class="form-control" style="border-color: #F44336" placeholder="请再次输入密码（必填）：核对密码"  />
              </div>
              <div>
                <input id="showname" type="text" class="form-control" style="border-color: #F44336" placeholder="显示名（必填）：登录网站后显示的名称" />
              </div>
              <div>
                <input id="email" type="email" class="form-control" placeholder="邮箱" />
              </div>
              <div>
                <input id="cellphone" type="text" class="form-control" placeholder="手机"/>
              </div>
              <div>
                <input id="wechart" type="text" class="form-control" placeholder="微信号" />
              </div>
                <div>
                    <table>
                        <tr>
                            <td><input id="validCode" type="text" class="form-control" style="border-color: #F44336" placeholder="验证码（必填）" /></td>
                            <td><img id="validImg" style="margin-left: 10px;margin-top: 0px;margin-bottom:20px;border:solid 1px;" src="/project/captcha/<?php echo $this->img;?>.png" onclick="reload()"></td>
                            <td><a class="btn btn-default submit"  style="margin-left: 10px;margin-top: 0px;margin-bottom:20px;" href="javascript:void(0);" onclick="registuser()">提 交</a></td>
                        </tr>
                    </table>

                </div>
              <div>

              </div>
              <div class="clearfix"></div>
              <div class="separator">
                <p class="change_link">已有账号？
                  <a id="login2" href="#signin" class="to_register"> 登录 </a>
                </p>
                <div class="clearfix"></div>
                <br />
                <div>
                  <p>©20168 All Rights Reserved.</p>
                </div>
              </div>
            </form>
          </section>
        </div>
      </div>
    </div>
  <!-- jQuery -->
  <script src="/project/vendors/jquery/dist/jquery.min.js"></script>
  <script>
      var userid="<?php echo $this->img?>";
      $(function(){
          //获取按钮焦点
          $('#enterbtn').focus();
          //失去焦点时
          $("#loginname").blur(function(){ $('#enterbtn').focus();});
          $("#loginpassword").blur(function(){ $('#enterbtn').focus();});
          //按下回车时
          $("#loginname").keydown(function(event) {
              if (event.keyCode == "13") {//keyCode=13是回车键
                  $("#enterbtn").click();
              }
          });
          $("#loginpassword").keydown(function(event) {
              if (event.keyCode == "13") {//keyCode=13是回车键
                  $("#enterbtn").click();
              }
          });
      });

      function userlogin()
     {
	  var username =  $("#loginname").val().trim(),
	 	 password =  $("#loginpassword").val().trim();
	  if(username=="")
      {
          alert('用户名不能为空')
          return;
      }
      if(password=="")
         {
             alert('密码不能为空')
             return;
         }
		$.post("/project/login/ajaxlogin",{ 
			username:username,
			password:password
		},
  		 function(data){	
			if(data[0].vali=="ok"){
				//验证通过
				window.location.href='/project/main/index';
		}else{
			alert("登录失败!\n"+data[0].vali);
		}
	 }, "json");
	}
	function registuser(){
		var username =  $("#username").val().trim(),
		    showname=$("#showname").val().trim(),
		    password =  $("#password").val().trim(),
		    password2 =  $("#password2").val().trim(),
		    email =  $("#email").val().trim(),
		    cellphone=$("#cellphone").val().trim(),
		    wechart=$("#wechart").val().trim(),
            validCode=$("#validCode").val().trim();

		if(username == "" ){
		alert("用户名不能为空");
		$("#username").focus();
		return;
		}
		if(showname == "" ){
			alert("显示名不能为空");
			$("#showname").focus();
			return;
			}
		if(cellphone!="")
		{
			if(!(/^1(3|4|5|7|8)\d{9}$/.test(cellphone.trim())) ){
				alert("手机号不正确");
				$("#cellphone").focus();
				return;
			}
		}
		if( password == ""|| password2==""){
			alert("密码不能空");
			$("#password").focus();
			return;
		}
		if( password != password2){
			alert("密码不一致");
			$("#password").focus();
			return;
		}
		if(email!=""){
			if( !(/^([a-zA-Z0-9_-])+@([a-zA-Z0-9_-])+(.[a-zA-Z0-9_-])+/.test(email.trim()))){
				alert("email错误");
				$("#email").focus();
				return;
			}
		}
        if(validCode == "" ){
            alert("验证码不能为空");
            $("#validCode").focus();
            return;
        }
		$.post("/project/user/register",{ 
			    username:username,
			    password:password,
			    email:email,
			    cellphone:cellphone,
			    showname:showname,
			    wechart:wechart,
                userid:userid,
                validCode:validCode
		},
  		 function(data){	
			if(data[0].username=="用户 OK"&&data[0].cellphone=="手机 OK"&&data[0].email=="邮箱 OK"&&data[0].code=="验证码 OK"){
				//验证通过
				alert("注册成功!\n");
				//js模拟点击a标签，触发href.
				//因为a标签的href属性是在他dom中的0里面，需要点击那个0才能实现，而数字型的属性名不能用“.”来获取，故写成[0]。
				$('#login2')[0].click();
				//清空数据
                $("#username").val('');
                $("#password").val('');
                $("#password2").val('');
                $("#showname").val('');
                $("#cellphone").val('');
                $("#wechart").val('');
                $("#email").val('');
                reload();
		}else{
			alert("注册失败!\n"+data[0].username+'\n'+data[0].cellphone+'\n'+data[0].email+'\n'+data[0].code+'\n');
			reload();
		}
	 }, "json");
	}
    //获取验证码
	function reload(){
        $.post("/project/login/ajaximg",{a:null},
            function(data){
                if(data!=null){
                    $('#validImg').attr('src',"/project/captcha/"+data+".png");
                    userid=data;
                }
                else//网络错误
                {ans= "err";}
            },'html');
        $("#validCode").val('');
    }

  </script>
  </body>
</html>
