<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>登录</title>
    <!-- Bootstrap -->
    <link href="/project/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="/project/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="/project/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- Animate.css -->
    <link href="/project/vendors/animate.css/animate.min.css" rel="stylesheet">
    <!-- Custom Theme Style -->
    <link href="/project/build/css/custom.min.css" rel="stylesheet">
  </head>
  <body class="login">
    <div>
      <a class="hiddenanchor" id="signup"></a>
      <a class="hiddenanchor" id="signin"></a>
      <div class="login_wrapper">
        <div class="animate form login_form">
          <section class="login_content">
            <form>
              <h1>登 录</h1>
              <div>
                <input id="loginname" type="text" class="form-control" placeholder="用户名" required="" />
              </div>
              <div>
                <input id="loginpassword" type="password" class="form-control" placeholder="密 码" required="" />
              </div>
              <div>
                <a class="btn btn-default submit" href="javascript:void(0);" onclick="userlogin()">确 认</a>
                <a class="reset_pass" href="#">忘记密码?</a>
              </div>
              <div class="clearfix"></div>
              <div class="separator">
                  <a href="#signup" class="to_register"> 创建账号 </a>
                <div class="clearfix"></div>
                <br />
                <div>
                  <p>©2018 All Rights Reserved.</p>
                </div>
              </div>
            </form>
          </section>
        </div>
        <div id="register" class="animate form registration_form">
          <section class="login_content">
            <form>
              <h1>创建账号</h1>
              <div>
                <input id="username" type="text" class="form-control" placeholder="用户名（必填）：登录网站的用户名" />
              </div>
                <div>
                <input  id="password" type="password" class="form-control" placeholder="密码（必填）：登录网站的密码"  />
              </div>
               <div>
                <input  id="password2" type="password" class="form-control" placeholder="请再次输入密码（必填）：核对密码"  />
              </div>
              <div>
                <input id="showname" type="text" class="form-control" placeholder="显示名（必填）：登录网站后显示的名称" />
              </div>
              <div>
                <input id="email" type="email" class="form-control" placeholder="邮箱" />
              </div>
              <div>
                <input id="cellphone" type="text" class="form-control" placeholder="手机"/>
              </div>
              <div>
                <input id="wechart" type="text" class="form-control" placeholder="微信号" />
              </div>
              <div>
                <a class="btn btn-default submit" href="javascript:void(0);" onclick="registuser()">提 交</a>
              </div>
              <div class="clearfix"></div>
              <div class="separator">
                <p class="change_link">已有账号？
                  <a id="login2" href="#signin" class="to_register"> 登录 </a>
                </p>
                <div class="clearfix"></div>
                <br />
                <div>
                  <p>©20168 All Rights Reserved.</p>
                </div>
              </div>
            </form>
          </section>
        </div>
      </div>
    </div>
  <!-- jQuery -->
  <script src="/project/vendors/jquery/dist/jquery.min.js"></script>
  <script>
  function userlogin()
  {
	  var username =  $("#loginname").val(),
	 	 password =  $("#loginpassword").val();
		$.post("/project/login/ajaxlogin",{ 
			username:username,
			password:password
		},
  		 function(data){	
			if(data[0].vali=="ok"){
				//验证通过
				window.location.href='/project/main/index';
		}else{
			alert("登录失败!\n"+data[0].vali);
		}
	 }, "json");
	}
	function registuser(){
		var username =  $("#username").val(),
		showname=$("#showname").val(),
		password =  $("#password").val(),
		password2 =  $("#password2").val(),
		email =  $("#email").val(),
		cellphone=$("#cellphone").val(),
		wechart=$("#wechart").val();

		if(username == "" ){
		alert("用户名不能为空");
		$("#username").focus();
		return;
		}
		if(showname == "" ){
			alert("显示名不能为空");
			$("#showname").focus();
			return;
			}
		if(cellphone!="")
		{
			if(!(/^1(3|4|5|7|8)\d{9}$/.test(cellphone.trim())) ){
				alert("手机号不正确");
				$("#cellphone").focus();
				return;
			}
		}
		if( password == ""|| password2==""){
			alert("密码不能空");
			$("#password").focus();
			return;
		}
		if( password != password2){
			alert("密码不一致");
			$("#password").focus();
			return;
		}
		if(email!=""){
			if( !(/^([a-zA-Z0-9_-])+@([a-zA-Z0-9_-])+(.[a-zA-Z0-9_-])+/.test(email.trim()))){
				alert("email错误");
				$("#email").focus();
				return;
			}
		}
		$.post("/project/user/register",{ 
			username:username,
			password:password,
			email:email,
			cellphone:cellphone,
			showname:showname,
			wechart:wechart
		},
  		 function(data){	
			if(data[0].username=="用户 OK"&&data[0].cellphone=="cellphone OK"&&data[0].email=="Email OK"){
				//验证通过
				alert("注册成功!\n");
				//js模拟点击a标签，触发href.
				//因为a标签的href属性是在他dom中的0里面，需要点击那个0才能实现，而数字型的属性名不能用“.”来获取，故写成[0]。
				$('#login2')[0].click();
		}else{
			alert("注册失败!\n"+data[0].username+'\n'+data[0].cellphone+'\n'+data[0].email+'\n');
		}
	 }, "json");
	}
  </script>
  </body>
</html>
