<ul class="list-unstyled msg_list">
    <?php if (count($this->paginator)): ?>
        <?php foreach ($this->paginator as $item): ?>
            <li>
                <div class="btn-group-vertical">
                    <a class="btn btn-primary btn-xs" href="/project/project/pro_level1?pro_num=<?php echo $item['pro_num'];?>" ><i class="fa fa-folder"></i> 查看 </a>
                    <?php if ($this->loginuser['role'] == 'admin'): ?>
                        <a class="btn btn-xs btn-info" href="/project/project/pro_level1_e?pro_num=<?php echo $item['pro_num'];?>"><i class="fa fa-pencil"></i> 编辑</a>
                        <a class="btn btn-xs btn-danger" onclick="deltalert('<?php echo $item['pro_num'];?>')"><i class="fa fa-trash-o"></i> 删除</a>
                    <?php endif; ?>
                </div>
                <a>
                    <span class="message">
                        <strong>项目编号：</strong><?php echo $item['pro_num']; ?>
                        <strong style="padding-left: 10px;">项目名称：</strong><?php echo $item['pro_name']; ?>
                    </span>
                    <span class="message" style="padding-top: 5px;padding-bottom: 5px;">
                        <strong>项目状态：</strong><?php if ($item['pro_status'] == '2'): ?>
                            <span class="label label-success">已完成</span>
                        <?php elseif ($item['pro_status'] == '1'): ?>
                            <span class="label label-primary">进行中</span>
                        <?php else: ?>
                            <span class="label label-default">未启动</span>
                        <?php endif; ?>
                    </span>
                    <span class="message">
                        <strong>项目内容：</strong>
                        <?php echo $item['pro_sub_content']; ?>
                    </span>
                </a>
            </li>
        <?php endforeach; ?>
    <?php endif; ?>
</ul>
<nav aria-label="Page navigation">
    <?php echo $this->paginationControl($this->paginator, 'Sliding', '/main/pagination.phtml', array('requestParams' => $this->requestParams)); ?>
</nav>
