<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>项目大厅 </title>

    <!-- Bootstrap -->
    <link href="../vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="../vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="../vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- iCheck -->
    <link href="../vendors/iCheck/skins/flat/green.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="../build/css/custom.min.css" rel="stylesheet">
</head>

<body class="nav-md">
<div class="container body">
    <div class="main_container">
        <div class="col-md-3 left_col">
            <div class="left_col scroll-view">
                <!--系统标题-->
                <div class="navbar nav_title" style="border: 0;">
                    <a href="/project/main/index" class="site_title">
                        <span>我们的系统</span>
                    </a>
                </div>
                <!--/系统标题-->
                <div class="clearfix"></div>
                <!-- 账户快捷信息 -->
                <div class="profile clearfix">
                    <div class="profile_pic">
                        <img src="/project/images/user.png" alt="..." class="img-circle profile_img">
                    </div>
                    <div class="profile_info">
                        <span>欢迎,</span>
                        <h2>
                            <?php echo $this->loginuser['showname'];?>
                        </h2>
                    </div>
                </div>
                <!-- /账户快捷信息 -->
                <br />
                <!-- 左侧目录菜单 -->
                <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                    <div class="menu_section">
                        <ul class="nav side-menu">
                            <li>
                                <a>
                                    <i class="fa fa-home"></i> 主页
                                    <span class="fa fa-chevron-down"></span>
                                </a>
                                <ul class="nav child_menu">
                                    <li>
                                        <a href="index">p1</a>
                                    </li>
                                    <li>
                                        <a href="project">project</a>
                                    </li>
                                    <li>
                                        <a href="index2.html">p2</a>
                                    </li>
                                    <li>
                                        <a href="index3.html">p3</a>
                                    </li>
                                    <li>
                                        <a href="index4.html">p4</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="menu_section">
                        <h3>设 置</h3>
                        <ul class="nav side-menu">
                            <li>
                                <a>
                                    <i class="fa fa-sitemap"></i> 权限管理
                                    <span class="fa fa-chevron-down"></span>
                                </a>
                                <ul class="nav child_menu">
                                    <li>
                                        <a href="tables_dynamic.html">空空荡荡</a>
                                    <li>
                                        <a>能展示三级菜单
                                            <span class="fa fa-chevron-down"></span>
                                        </a>
                                        <ul class="nav child_menu">
                                            <li class="sub_menu">
                                                <a href="#">哈哈1</a>
                                            </li>
                                            <li>
                                                <a href="#">哈哈2</a>
                                            </li>
                                            <li>
                                                <a href="#">哈哈3</a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li>
                                        <a href="#level1_2">空空荡荡</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>

                </div>
                <!-- /左侧目录菜单 -->
            </div>
        </div>

        <!-- 顶部导航栏 -->
        <div class="top_nav">
            <div class="nav_menu">
                <nav>
                    <div class="nav toggle">
                        <a id="menu_toggle">
                            <i class="fa fa-bars"></i>
                        </a>
                    </div>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="">
                            <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                <img src="/project/images/user.png" alt="">
                                <?php echo $this->loginuser['showname'];?>
                                <span class=" fa fa-angle-down"></span>
                            </a>
                            <ul class="dropdown-menu dropdown-usermenu pull-right">
                                <li>
                                    <a href="/project/user/index">
                                        <span> 设 置 </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="/project/login/logout">
                                        <i class="fa fa-sign-out pull-right"></i> 退 出 </a>
                                </li>
                            </ul>
                        </li>

                        <li role="presentation" class="dropdown">
                            <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                                <i class="fa fa-envelope-o"></i>
                            </a>
                            <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                                <li>
                                    <div class="text-center">
                                        <a>
                                            <strong>所有消息</strong>
                                            <i class="fa fa-angle-right"></i>
                                        </a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
        <!-- /顶部导航栏 -->

        <!-- 页面内容 -->
        <div class="right_col" role="main">
            <div class="">
                <div class="page-title">
                    <div class="title_left">
                        <h3>当前项目列表</h3>
                    </div>

                    <div class="title_right">
                        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="搜索...">
                                <span class="input-group-btn">
                      <button class="btn btn-default" type="button">前往</button>
                    </span>
                            </div>
                        </div>
                    </div>
                </div>



                <div class="row">
                    <div class="col-md-12">
                        <div class="x_panel">
                            <div class="x_title">
                                <h2>2018/6/25</h2>

                                <div class="clearfix"></div>
                            </div>
                            <div class="x_content">

                                <p>具有项目列表以及项目进度条</p>

                                <!-- start project list -->
                                <table class="table table-striped projects">
                                    <thead>
                                    <tr>
                                        <th style="width: 8%">项目序号</th>
                                        <th style="width: 20%">项目名称</th>
                                        <th>项目跟进成员</th>
                                        <th>项目进度</th>
                                        <th>项目状态</th>
                                        <th style="width: 20%">编辑</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td>1</td>
                                        <td>
                                            <a href="index">奉贤区睦邻点”四间房“运营管理技术支持项目01</a>
                                            <br />
                                            <small>创立日期：2018年05月01日</small>
                                        </td>
                                        <td>
                                            <ul class="list-inline">
                                                <li>
                                                    <img src="/project/images/user.png"  class="avatar" alt="...">
                                                    <p>潘飞</p>
                                                </li>

                                                <li>
                                                    <img src="/project/images/user.png"  class="avatar" alt="...">
                                                    <p>张三</p>
                                                </li>
                                                <li>
                                                    <img src="/project/images/user.png"  class="avatar" alt="...">
                                                    <p>李四</p>
                                                </li>
                                                <li>
                                                    <img src="/project/images/user.png"  class="avatar" alt="...">
                                                    <p>王五</p>
                                                </li>

                                            </ul>
                                        </td>
                                        <td class="project_progress">
                                            <div class="progress progress_sm">
                                                <div class="progress-bar bg-green" role="progressbar" data-transitiongoal="57"></div>
                                            </div>
                                            <small>项目完成进度：57% </small>
                                        </td>
                                        <td>
                                            <button type="button" class="btn btn-success btn-xs">进行中</button>
                                        </td>
                                        <td>
                                            <a href="index" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> 查看 </a>
                                            <a href="#" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> 编辑 </a>
                                            <a href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> 删除 </a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>2</td>
                                        <td>
                                            <a href="index">奉贤区睦邻点”四间房“运营管理技术支持项目02</a>
                                            <br />
                                            <small>创立日期：2018年05月02日</small>
                                        </td>
                                        <td>
                                            <ul class="list-inline">
                                                <li>
                                                    <img src="/project/images/user.png"  class="avatar" alt="...">
                                                    <p>潘飞</p>
                                                </li>

                                                <li>
                                                    <img src="/project/images/user.png"  class="avatar" alt="...">
                                                    <p>张三</p>
                                                </li>
                                                <li>
                                                    <img src="/project/images/user.png"  class="avatar" alt="...">
                                                    <p>李四</p>
                                                </li>
                                                <li>
                                                    <img src="/project/images/user.png"  class="avatar" alt="...">
                                                    <p>王五</p>
                                                </li>

                                            </ul>
                                        </td>
                                        <td class="project_progress">
                                            <div class="progress progress_sm">
                                                <div class="progress-bar bg-green" role="progressbar" data-transitiongoal="100"></div>
                                            </div>
                                            <small>项目完成进度：100% </small>
                                        </td>
                                        <td>
                                            <button type="button" class="btn btn-primary btn-xs">已完成</button>
                                        </td>
                                        <td>
                                            <a href="index" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> 查看 </a>
                                            <a href="#" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> 编辑 </a>
                                            <a href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> 删除 </a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>3</td>
                                        <td>
                                            <a href="index">奉贤区睦邻点”四间房“运营管理技术支持项目03</a>
                                            <br />
                                            <small>创立日期：2018年05月03日</small>
                                        </td>
                                        <td>
                                            <ul class="list-inline">
                                                <li>
                                                    <img src="/project/images/user.png"  class="avatar" alt="...">
                                                    <p>潘飞</p>
                                                </li>

                                                <li>
                                                    <img src="/project/images/user.png"  class="avatar" alt="...">
                                                    <p>张三</p>
                                                </li>
                                                <li>
                                                    <img src="/project/images/user.png"  class="avatar" alt="...">
                                                    <p>李四</p>
                                                </li>
                                                <li>
                                                    <img src="/project/images/user.png"  class="avatar" alt="...">
                                                    <p>王五</p>
                                                </li>

                                            </ul>
                                        </td>
                                        <td class="project_progress">
                                            <div class="progress progress_sm">
                                                <div class="progress-bar bg-green" role="progressbar" data-transitiongoal="0"></div>
                                            </div>
                                            <small>项目完成进度：0% </small>
                                        </td>
                                        <td>
                                            <button type="button" class="btn btn-danger btn-xs">未开始</button>
                                        </td>
                                        <td>
                                            <a href="index" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> 查看 </a>
                                            <a href="#" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> 编辑 </a>
                                            <a href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> 删除 </a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>4</td>
                                        <td>
                                            <a href="index">奉贤区睦邻点”四间房“运营管理技术支持项目04</a>
                                            <br />
                                            <small>创立日期：2018年05月01日</small>
                                        </td>
                                        <td>
                                            <ul class="list-inline">
                                                <li>
                                                    <img src="/project/images/user.png"  class="avatar" alt="...">
                                                    <p>潘飞</p>
                                                </li>

                                                <li>
                                                    <img src="/project/images/user.png"  class="avatar" alt="...">
                                                    <p>张三</p>
                                                </li>
                                                <li>
                                                    <img src="/project/images/user.png"  class="avatar" alt="...">
                                                    <p>李四</p>
                                                </li>
                                                <li>
                                                    <img src="/project/images/user.png"  class="avatar" alt="...">
                                                    <p>王五</p>
                                                </li>

                                            </ul>
                                        </td>
                                        <td class="project_progress">
                                            <div class="progress progress_sm">
                                                <div class="progress-bar bg-green" role="progressbar" data-transitiongoal="75"></div>
                                            </div>
                                            <small>项目完成进度：75% </small>
                                        </td>
                                        <td>
                                            <button type="button" class="btn btn-success btn-xs">进行中</button>
                                        </td>
                                        <td>
                                            <a href="index" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> 查看 </a>
                                            <a href="#" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> 编辑 </a>
                                            <a href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> 删除 </a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>5</td>
                                        <td>
                                            <a href="index">奉贤区睦邻点”四间房“运营管理技术支持项目05</a>
                                            <br />
                                            <small>创立日期：2018年05月01日</small>
                                        </td>
                                        <td>
                                            <ul class="list-inline">
                                                <li>
                                                    <img src="/project/images/user.png"  class="avatar" alt="...">
                                                    <p>潘飞</p>
                                                </li>

                                                <li>
                                                    <img src="/project/images/user.png"  class="avatar" alt="...">
                                                    <p>张三</p>
                                                </li>
                                                <li>
                                                    <img src="/project/images/user.png"  class="avatar" alt="...">
                                                    <p>李四</p>
                                                </li>
                                                <li>
                                                    <img src="/project/images/user.png"  class="avatar" alt="...">
                                                    <p>王五</p>
                                                </li>

                                            </ul>
                                        </td>
                                        <td class="project_progress">
                                            <div class="progress progress_sm">
                                                <div class="progress-bar bg-green" role="progressbar" data-transitiongoal="20"></div>
                                            </div>
                                            <small>项目完成进度：20% </small>
                                        </td>
                                        <td>
                                            <button type="button" class="btn btn-success btn-xs">进行中</button>
                                        </td>
                                        <td>
                                            <a href="index" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> 查看 </a>
                                            <a href="#" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> 编辑 </a>
                                            <a href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> 删除 </a>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                                <!-- end project list -->

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
            <div class="pull-right">
                Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
            </div>
            <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
    </div>
</div>

<!-- jQuery -->
<script src="../vendors/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="../vendors/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- FastClick -->
<script src="../vendors/fastclick/lib/fastclick.js"></script>
<!-- NProgress -->
<script src="../vendors/nprogress/nprogress.js"></script>
<!-- bootstrap-progressbar -->
<script src="../vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>

<!-- Custom Theme Scripts -->
<script src="../build/js/custom.min.js"></script>
</body>
</html>