<?php if(count($this->paginator)): ?>
    <table class="table table-striped table-bordered" id="datatable-buttons">
        <thead>
        <tr>
            <th style="width:30px">操作</th>
            <th style="width:200px">思考</th>
            <th style="width:400px">分析</th>
        </tr>
        </thead>
        <tbody style="font-size:12px;">
        <?php foreach($this->paginator as $item): ?>
            <tr>
                <td>
                    <?php if ($this->loginuser['role'] == 'admin'): ?>
                        <div class="btn-group-vertical">
                            <button class="btn btn-xs btn-primary" type="button" onclick="editanalysis(<?php echo $this->page;?>,<?php echo $item['id'];?>)">编辑</button>
                            <button class="btn btn-xs btn-danger" type="button" onclick="deltanalysis(<?php echo $this->page;?>,<?php echo $item['id'];?>)">删除</button>
                        </div>
                    <?php endif;?>

                </td>
                <td><?php echo $item['pro_problem'];?></td>
                <td><?php echo $item['pro_solve'];?></td>
            </tr>
        <?php endforeach;?>
        </tbody>
    </table>
<?php endif;?>
<nav aria-label="Page navigation">
    <?php echo $this->paginationControl($this->paginator, 'Sliding', '/project/pagination.phtml', array('requestParams' => $this->requestParams));?>
</nav>