<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="/project/images/favicon.ico" type="image/ico" />
    <title><?php echo $this->project_data[0]['pro_name']?></title>
    <!-- Bootstrap -->
    <link href="/project/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome 图标和字体库css框架-->
    <link href="/project/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress 前端必备进度条样式-->
    <link href="/project/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- iCheck 一款对checkbox的美化样式-->
    <link href="/project/vendors/iCheck/skins/flat/green.css" rel="stylesheet">
    <!-- bootstrap-progressbar 实现大文件上传的进度条样式-->
    <link href="/project/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
    <!-- JQVMap 地图样式
    <!--<link href="/project/vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet" />-->
    <!-- bootstrap-daterangepicker 日历样式-->
    <link href="/project/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">

    <!-- Custom Theme Style 基础风格模板样式-->
    <link href="/project/build/css/custom.min.css" rel="stylesheet">

    <!-- Datatables 表格的一些美化样式-->
    <link href="/project/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <link href="/project/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
    <link href="/project/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
    <link href="/project/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
    <link href="/project/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">
    <!-- PNotify 消息提醒样式-->
    <link href="/project/vendors/pnotify/dist/pnotify.css" rel="stylesheet">
    <link href="/project/vendors/pnotify/dist/pnotify.buttons.css" rel="stylesheet">
    <link href="/project/vendors/pnotify/dist/pnotify.nonblock.css" rel="stylesheet">
    <style>
        /*定义滚动条高宽及背景 高宽分别对应横竖滚动条的尺寸*/
        ::-webkit-scrollbar
        {
            width: 5px;
            height: 12px;
            background-color: #a5a5a5;
        }
        /*定义滚动条轨道 内阴影+圆角*/
        ::-webkit-scrollbar-track
        {background-color: #a5a5a5;}
        /*定义滑块 内阴影+圆角*/
        ::-webkit-scrollbar-thumb
        {background-color: #666;}
    </style>
</head>

<body class="nav-md">
<!-- 模态框 -->
<div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">弹出框</h4>
            </div>
            <div class="modal-body">
                <div id="content">sssssss</div>
            </div>
        </div>
    </div>
</div>
<!--/模态框 -->
<div class="container body">
    <div class="main_container">
        <!--侧边栏-->
        <div class="col-md-3 left_col">
            <div class="left_col scroll-view">
                <!--系统标题-->
                <div class="navbar nav_title" style="border: 0;">
                    <a href="/project/main/index" class="site_title">
                        <span>我们的系统</span>
                    </a>
                </div>
                <!--/系统标题-->
                <div class="clearfix"></div>
                <!-- 账户快捷信息 -->
                <div class="profile clearfix">
                    <div class="profile_pic">
                        <img src="/project/images/user.png" alt="..." class="img-circle profile_img">
                    </div>
                    <div class="profile_info">
                        <span>欢迎,</span>
                        <h2>
                            <?php echo $this->loginuser['showname'];?>
                        </h2>
                    </div>
                </div>
                <!-- /账户快捷信息 -->
                <br />
                <!-- 左侧目录菜单 -->
                <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                    <div class="menu_section">
                        <ul class="nav side-menu">
                            <li  class="active">
                                <a>
                                    <i class="fa fa-home"></i> 功能
                                    <span class="fa fa-chevron-down"></span>
                                </a>
                                <ul class="nav child_menu" style="display: block;">
                                    <li class="current-page">
                                        <a href="/project/main/index">项目管理</a>
                                    </li>
                                    <li>
                                        <a href="index2.html">p2</a>
                                    </li>
                                    <li>
                                        <a href="index3.html">p3</a>
                                    </li>
                                    <li>
                                        <a href="index4.html">p4</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="menu_section">
                        <h3>设 置</h3>
                        <ul class="nav side-menu">
                            <li>
                                <a>
                                    <i class="fa fa-sitemap"></i> 权限管理
                                    <span class="fa fa-chevron-down"></span>
                                </a>
                                <ul class="nav child_menu">
                                    <li>
                                        <a href="tables_dynamic.html">空空荡荡</a>
                                    <li>
                                        <a>能展示三级菜单
                                            <span class="fa fa-chevron-down"></span>
                                        </a>
                                        <ul class="nav child_menu">
                                            <li class="sub_menu">
                                                <a href="#">哈哈1</a>
                                            </li>
                                            <li>
                                                <a href="#">哈哈2</a>
                                            </li>
                                            <li>
                                                <a href="#">哈哈3</a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li>
                                        <a href="#level1_2">空空荡荡</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>

                </div>
                <!-- /左侧目录菜单 -->
            </div>
        </div>
        <!--/侧边栏-->
        <!-- 顶部导航栏 -->
        <div class="top_nav">
            <div class="nav_menu">
                <nav>
                    <div class="nav toggle">
                        <a id="menu_toggle">
                            <i class="fa fa-bars"></i>
                        </a>
                    </div>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="">
                            <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                <img src="/project/images/user.png" alt="">
                                <?php echo $this->loginuser['showname'];?>
                                <span class=" fa fa-angle-down"></span>
                            </a>
                            <ul class="dropdown-menu dropdown-usermenu pull-right">
                                <li>
                                    <a href="/project/user/index">
                                        <span> 设 置 </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="/project/login/logout">
                                        <i class="fa fa-sign-out pull-right"></i> 退 出 </a>
                                </li>
                            </ul>
                        </li>

                        <li role="presentation" class="dropdown">
                            <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                                <i class="fa fa-envelope-o"></i>
                            </a>
                            <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                                <li>
                                    <div class="text-center">
                                        <a>
                                            <strong>所有消息</strong>
                                            <i class="fa fa-angle-right"></i>
                                        </a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
        <!-- /顶部导航栏 -->

        <!-- 页面内容 -->
        <div class="right_col" role="main" style="min-height: 1600px;">
            <!-- 页面标题 -->
            <div class="page-title">
                <div class="title_left">

                </div>
            </div>
            <div class="clearfix"></div>
            <!-- /页面标题 -->
            <!-- 板块1 -->
            <div class="row">
                <div class="col-md-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2><strong><?php echo $this->project_data[0]['pro_name']?></strong></h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <div class="" role="tabpanel" data-example-id="togglable-tabs">
                                <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                                    <li role="presentation" class="active"><a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">一级项目主页</a>
                                    </li>
                                    <li role="presentation" class=""><a href="#tab_content2" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">二级项目目录</a>
                                    </li>
                                </ul>
                                <div id="myTabContent" class="tab-content">
                                    <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
                                        <form class="form-horizontal form-label-left" style="padding-bottom: 10px;">
                                            <div class="item form-group">
                                                <label class="control-label col-md-2 col-sm-3 col-xs-12">项目编号</label>
                                                <div class="col-md-3 col-sm-6 col-xs-12">
                                                    <input type="text" class="form-control" id="pro_num" name="pro_num">
                                                </div>
                                                <label class="control-label col-md-2 col-sm-3 col-xs-12" for="pro_name">项目名称</label>
                                                <div class="col-md-3 col-sm-6 col-xs-12">
                                                    <input id="pro_name" name="pro_name" class="form-control col-md-2 col-xs-12" type="text">
                                                </div>
                                            </div>
                                            <div class="item form-group">
                                                <label class="control-label col-md-2 col-sm-3 col-xs-12" for="pro_address01">项目归属</label>
                                                <div class="col-md-3 col-sm-6 col-xs-12">
                                                    <input type="text" id="pro_address01" name="pro_address01" class="form-control col-md-7 col-xs-12">
                                                </div>
                                                <label class="control-label col-md-2 col-sm-3 col-xs-12" for="pro_address02">项目实施地点</label>
                                                <div class="col-md-3 col-sm-6 col-xs-12">
                                                    <input type="text" id="pro_address02" name="pro_address02" class="form-control col-md-7 col-xs-12">
                                                </div>
                                            </div>
                                            <div class="item form-group">
                                                <label class="control-label col-md-2 col-sm-3 col-xs-12">服务对象</label>
                                                <div class="col-md-3 col-sm-6 col-xs-12">
                                                    <input type="text" class="form-control" id="pro_serviceObj" name="pro_serviceObj">
                                                </div>
                                                <label class="control-label col-md-2 col-sm-3 col-xs-12" for="pro_payMethod">付款方式</label>
                                                <div class="col-md-3 col-sm-6 col-xs-12">
                                                    <select id="pro_payMethod" name="pro_payMethod" class="select2_group form-control" placeholder="">
                                                        <optgroup label="网上支付">
                                                            <option value="AK2">请选择</option>
                                                            <option value="AK">微信</option>
                                                            <option value="HI">支付宝</option>
                                                        </optgroup>
                                                        <optgroup label="当面支付">
                                                            <option value="CA">现金</option>
                                                            <option value="NV">其他</option>
                                                        </optgroup>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="item form-group">
                                                <label class="control-label col-md-2 col-sm-3 col-xs-12" for="pro_reportMoney">申报金额</label>
                                                <div class="col-md-3 col-sm-6 col-xs-12">
                                                    <div class="input-group">
                                                        <input id="pro_reportMoney" name="pro_reportMoney" class="form-control col-md-7 col-xs-12" type="text">
                                                        <span class="input-group-addon">元</span>
                                                    </div>
                                                </div>

                                                <label class="control-label col-md-2 col-sm-3 col-xs-12" for="pro_endMoney">最高限价</label>
                                                <div class="col-md-3 col-sm-6 col-xs-12">
                                                    <div class="input-group">
                                                        <input id="pro_endMoney" name="pro_endMoney" class="form-control col-md-7 col-xs-12"  type="text">
                                                        <span class="input-group-addon">元</span>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="item form-group">
                                                <label class="control-label col-md-2 col-sm-3 col-xs-12" for="pro_startTime">项目开始时间</label>
                                                <div class="col-md-3 col-sm-6 col-xs-12">
                                                    <input type="text" class="form-control has-feedback-left mydatepicker" id="pro_startTime" name="pro_startTime" readonly="readonly">
                                                    <span class="fa fa-calendar-o form-control-feedback left" aria-hidden="true"></span>
                                                </div>

                                                <label class="control-label col-md-2 col-sm-3 col-xs-12" for="pro_endTime">项目结束时间</label>
                                                <div class="col-md-2 col-sm-6 col-xs-12">
                                                    <input type="text" class="form-control has-feedback-left mydatepicker" id="pro_endTime" name="pro_endTime" readonly="readonly">
                                                    <span class="fa fa-calendar-o form-control-feedback left" aria-hidden="true"></span>
                                                </div>
                                                总周期:<span class="badge bg-blue" id="total_time">0</span>个月
                                            </div>

                                            <div class="item form-group">
                                                <label class="control-label col-md-2 col-sm-3 col-xs-12" for="pro_type">所属项目类型</label>
                                                <div class="col-md-3 col-sm-6 col-xs-12">
                                                    <select id="pro_type" name="pro_type" class="select2_group form-control">
                                                        <optgroup label="类型标题1">
                                                            <option value="AK2">请选择</option>
                                                            <option value="AK">类型值1</option>
                                                            <option value="HI">类型值2</option>
                                                        </optgroup>
                                                        <optgroup label="Pacific Time Zone">
                                                            <option value="CA">California</option>
                                                            <option value="NV">Nevada</option>
                                                            <option value="OR">Oregon</option>
                                                            <option value="WA">Washington</option>
                                                        </optgroup>
                                                        <optgroup label="Mountain Time Zone">
                                                            <option value="AZ">Arizona</option>
                                                            <option value="CO">Colorado</option>
                                                            <option value="ID">Idaho</option>
                                                            <option value="MT">Montana</option>
                                                            <option value="NE">Nebraska</option>
                                                            <option value="NM">New Mexico</option>
                                                            <option value="ND">North Dakota</option>
                                                            <option value="UT">Utah</option>
                                                            <option value="WY">Wyoming</option>
                                                        </optgroup>
                                                    </select>
                                                </div>

                                                <label class="control-label col-md-2 col-sm-3 col-xs-12" for="pro_enterPeople">递交项目文本</label>
                                                <div class="col-md-3 col-sm-6 col-xs-12">
                                                    <input id="pro_sub_content" name="pro_sub_content" class="form-control col-md-7 col-xs-12"  placeholder=""  type="text">
                                                </div>
                                            </div>

                                            <div class="item form-group">
                                                <div class="accordion" id="accordion" role="tablist" aria-multiselectable="true">
                                                    <div class="panel">
                                                        <a class="panel-heading" role="tab" id="headingOne" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                                            <h6 class="panel-title">项目需求方信息</h6>
                                                        </a>
                                                        <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne" aria-expanded="true">
                                                            <div class="panel-body">

                                                                <div class="item form-group">
                                                                    <label class="control-label col-md-2 col-sm-3 col-xs-12" for="pro_type">需求单位</label>
                                                                    <div class="col-md-3 col-sm-6 col-xs-12">
                                                                        <input id="pro_dem_company" name="pro_dem_company" class="form-control col-md-7 col-xs-12" placeholder=""  type="text">
                                                                    </div>
                                                                    <label class="control-label col-md-2 col-sm-3 col-xs-12" for="pro_enterPeople">联系人</label>
                                                                    <div class="col-md-3 col-sm-6 col-xs-12">
                                                                        <input id="pro_dem_contacts" name="pro_dem_contacts" class="form-control col-md-7 col-xs-12"  placeholder=""  type="text">
                                                                    </div>

                                                                </div>
                                                                <div class="item form-group">
                                                                    <label class="control-label col-md-2 col-sm-3 col-xs-12" for="pro_type">联系电话</label>
                                                                    <div class="col-md-3 col-sm-6 col-xs-12">
                                                                        <input id="pro_dem_mobile" name="pro_dem_mobile" class="form-control col-md-7 col-xs-12" placeholder=""  type="text">
                                                                    </div>

                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="panel">
                                                        <a class="panel-heading collapsed" role="tab" id="headingTwo" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                                                            <h6 class="panel-title">项目代理方信息</h6>
                                                        </a>
                                                        <div id="collapseTwo" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingTwo" aria-expanded="true">
                                                            <div class="panel-body">
                                                                <div class="item form-group">
                                                                    <label class="control-label col-md-2 col-sm-3 col-xs-12" for="pro_enterPeople">代理单位</label>
                                                                    <div class="col-md-3 col-sm-6 col-xs-12">
                                                                        <input id="pro_agent_company" name="pro_agent_company" class="form-control col-md-7 col-xs-12" placeholder="" type="text">
                                                                    </div>
                                                                    <label class="control-label col-md-2 col-sm-3 col-xs-12" for="pro_type">联系人</label>
                                                                    <div class="col-md-3 col-sm-6 col-xs-12">
                                                                        <input id="pro_agent_contacts" name="pro_agent_contacts" class="form-control col-md-7 col-xs-12" placeholder=""  type="text">
                                                                    </div>
                                                                </div>
                                                                <div class="item form-group">
                                                                    <label class="control-label col-md-2 col-sm-3 col-xs-12" for="pro_enterPeople">联系电话</label>
                                                                    <div class="col-md-3 col-sm-6 col-xs-12">
                                                                        <input id="pro_agent_mobile" name="pro_agent_mobile" class="form-control col-md-7 col-xs-12"  placeholder="" type="text">
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <br>
                                            <div class="item form-group">
                                                <label class="control-label col-md-2 col-sm-3 col-xs-12" for="pro_type">承接组织需具备的条件</label>
                                                <div class="col-md-8 col-sm-6 col-xs-12">
                                                    <input id="pro_condition" name="pro_condition" class="form-control col-md-7 col-xs-12" placeholder=""  type="text">
                                                </div>
                                            </div>

                                            <div class="item form-group">
                                                <label class="control-label col-md-2 col-sm-3 col-xs-12" for="pro_content">项目监管要求</label>
                                                <div class="col-md-8 col-sm-8 col-xs-12">
                                                    <textarea id="pro_manage_require" name="pro_manage_require" class="form-control col-md-7 col-xs-12"></textarea>
                                                </div>
                                            </div>
                                            <div class="item form-group">
                                                <label class="control-label col-md-2 col-sm-3 col-xs-12" for="pro_content">项目结案要求</label>
                                                <div class="col-md-8 col-sm-8 col-xs-12">
                                                    <textarea id="pro_endCase_require" name="pro_endCase_require" class="form-control col-md-7 col-xs-12"></textarea>
                                                </div>
                                            </div>
                                            <div class="item form-group">

                                                <label class="control-label col-md-2 col-sm-3 col-xs-12" for="pro_content">项目内容</label>
                                                <div class="col-md-8 col-sm-8 col-xs-12">
                                                    <textarea id="pro_content" name="pro_content" class="form-control col-md-7 col-xs-12"></textarea>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                    <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab">

                                    </div>
                                </div>
                            </div>


                        </div>
                    </div>
                </div>
            </div>
            <!-- /板块1 -->
            <!-- 板块2 -->
            <div class="row">
                <div class="col-md-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <strong>对项目内容的思考与分析:&nbsp;</strong>
                            <a class="btn btn-primary btn-xs" onclick="createalert('<?php echo $this->project_data[0]['pro_num']?>')">增加</a>
                            <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <div class="col-md-12" id="pro_analysis_list">
                                <?php if(count($this->paginator)): ?>
                                    <table class="table table-striped table-bordered" id="datatable-buttons">
                                        <thead>
                                        <tr>
                                            <th style="width:30px">操作</th>
                                            <th style="width:200px">思考</th>
                                            <th style="width:400px">分析</th>
                                        </tr>
                                        </thead>
                                        <tbody style="font-size:12px;">
                                        <?php foreach($this->paginator as $item): ?>
                                            <tr>
                                                <td>
                                                    <?php if ($this->loginuser['role'] == 'admin'): ?>
                                                        <div class="btn-group-vertical">
                                                            <a class="btn btn-xs btn-primary" type="button" onclick="editanalysis(1,<?php echo $item['id'];?>)">编辑</a>
                                                            <a class="btn btn-xs btn-danger" type="button" onclick="deltanalysisalert(1,<?php echo $item['id'];?>)">删除</a>
                                                        </div>
                                                    <?php endif;?>

                                                </td>
                                                <td data-placement="top" data-toggle="tooltip" data-original-title="问题于<?php echo $item['createTime'].'由'.$item['createPeople'];?>提出"><?php echo $item['pro_problem'];?></td>
                                                <td><?php echo $item['pro_solve'];?></td>
                                            </tr>
                                        <?php endforeach;?>
                                        </tbody>
                                    </table>
                                <?php endif;?>
                                <nav aria-label="Page navigation">
                                    <?php echo $this->paginationControl($this->paginator, 'Sliding', '/proanalysis/pagination.phtml', array('requestParams' => $this->requestParams));?>
                                </nav>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <!-- /板块2 -->
        </div>
        <!-- /页面内容 -->

        <!-- 页脚 -->
        <footer>
            <div class="pull-right"></div>
            <div class="clearfix"></div>
        </footer>
        <!-- /页脚 -->
    </div>
</div>

<!-- jQuery -->
<script src="/project/vendors/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="/project/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- FastClick 消除点击延时提高程序的运行效率-->
<script src="/project/vendors/fastclick/lib/fastclick.js"></script>
<!-- NProgress 进度条插件-->
<script src="/project/vendors/nprogress/nprogress.js"></script>
<!-- Chart.js 图表工具-->
<script src="/project/vendors/Chart.js/dist/Chart.min.js"></script>
<!-- gauge.js 动态仪表盘插件-->
<script src="/project/vendors/gauge.js/dist/gauge.min.js"></script>
<!-- bootstrap-progressbar 大文件上传进度条-->
<script src="/project/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
<!-- iCheck 一款对checkbox的美化插件-->
<script src="/project/vendors/iCheck/icheck.min.js"></script>
<!-- Skycons 天气插件-->
<!-- <script src="/project/vendors/skycons/skycons.js"></script>-->
<!-- Flot 绘图工具-->
<!-- <script src="/project/vendors/Flot/jquery.flot.js"></script>
<script src="/project/vendors/Flot/jquery.flot.pie.js"></script>
<script src="/project/vendors/Flot/jquery.flot.time.js"></script>
<script src="/project/vendors/Flot/jquery.flot.stack.js"></script>
<script src="/project/vendors/Flot/jquery.flot.resize.js"></script>-->
<!-- Flot plugins 图表插件-->
<!-- <script src="/project/vendors/flot.orderbars/js/jquery.flot.orderBars.js"></script>
<script src="/project/vendors/flot-spline/js/jquery.flot.spline.min.js"></script>
<script src="/project/vendors/flot.curvedlines/curvedLines.js"></script>-->
<!-- DateJS 日期插件-->
<script src="/project/vendors/DateJS/build/date.js"></script>
<!-- JQVMap 地图插件-->
<!-- <script src="/project/vendors/jqvmap/dist/jquery.vmap.js"></script>
<script src="/project/vendors/jqvmap/dist/maps/jquery.vmap.world.js"></script>
<script src="/project/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js"></script>-->
<!-- bootstrap-daterangepicker 双日历日期选择器插件-->
<script src="/project/vendors/moment/min/moment.min.js"></script>
<script src="/project/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>
<!-- Datatables 表格插件-->
<script src="/project/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="/project/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
<script src="/project/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
<script src="/project/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
<script src="/project/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
<script src="/project/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
<script src="/project/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
<script src="/project/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
<script src="/project/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
<script src="/project/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
<script src="/project/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
<script src="/project/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
<script src="/project/vendors/jszip/dist/jszip.min.js"></script>
<script src="/project/vendors/pdfmake/build/pdfmake.min.js"></script>
<script src="/project/vendors/pdfmake/build/vfs_fonts.js"></script>
<!-- Custom Theme Scripts -->
<script src="/project/build/js/custom.min.js"></script>
<!-- PNotify 消息提醒插件 -->
<script src="/project/vendors/pnotify/dist/pnotify.js"></script>
<script src="/project/vendors/pnotify/dist/pnotify.buttons.js"></script>
<script src="/project/vendors/pnotify/dist/pnotify.nonblock.js"></script>
</body>
<script type="text/javascript">
        var origin = new Array();
        origin = <?php echo json_encode($this->project_data[0]);?>;
        function getmonth(starttime,endtime)
        {
            var date1=new Date(starttime);
            var y1 = date1.getFullYear();
            var m1 = date1.getMonth() + 1;
            var date2=new Date(endtime);
            var y2 = date2.getFullYear();
            var m2 = date2.getMonth() + 1;
            return Math.abs((y2-y1)*12+m2-m1);
        }


        $("#pro_startTime").change(function(){
            months=getmonth($("#pro_startTime").val(),$("#pro_endTime").val());
            $('#total_time').html(months);
        });
        $("#pro_endTime").change(function(){
            months=getmonth($("#pro_startTime").val(),$("#pro_endTime").val());
            $('#total_time').html(months);
        });

        //创建项目分析
        function createalert(pro_num) {
            $('#myModal1').modal('show');
            $('.modal-title').empty();
            $('.modal-title').html('添加'+'<strong><?php echo $this->project_data[0]['pro_name']?></strong>'+'项目分析');
            $('#content').empty();
            htmltext="<form id=\"demo-form2\" data-parsley-validate=\"\" class=\"form-horizontal form-label-left\" novalidate=\"\">\n" +
                "<div class=\"form-group\">\n" +
                "     <label class=\"control-label col-md-2 col-sm-2 col-xs-12\">思考</label>\n" +
                "     <div class=\"col-md-10 col-sm-10 col-xs-12\">\n" +
                "         <textarea class=\"form-control\" rows=\"4\" id=\"addproblem\"></textarea>\n" +
                "     </div>\n" +
                "</div>\n" +
                "<div class=\"form-group\">\n" +
                "      <label class=\"control-label col-md-2 col-sm-2 col-xs-12\">分析</label>\n" +
                "      <div class=\"col-md-10 col-sm-10 col-xs-12\">\n" +
                "         <textarea class=\"form-control\" rows=\"4\" id=\"addsolve\"></textarea>\n" +
                "      </div>\n" +
                "</div>\n" +
                "<div class=\"ln_solid\"></div>\n" +
                "<div class=\"form-group\">\n" +
                "      <div class=\"col-md-6 col-sm-6 col-xs-12 col-md-offset-3\">\n" +
                "         <a class=\"btn btn-primary\" type=\"button\" data-dismiss=\"modal\">取消</a>\n" +
                "         <a type=\"submit\" class=\"btn btn-success\" data-dismiss=\"modal\" onclick=\"createanalysis()\">提交</a>\n" +
                "      </div>\n" +
                "</div>\n" +
                "</form>";
            $('#content').html(htmltext);
        }
        //增加项目分析
        function createanalysis()
        {

            var addproblem=$('#addproblem').val().trim(), addsolve=$('#addsolve').val().trim();
            if(addproblem==''||addsolve=='')
            {
                alert("创建项目分析<?php echo $this->project_data[0]['pro_name']?>失败！\n思考或分析不能为空！");
                return;
            }
            $.ajaxSetup({async: true});
            $.post("/project/proanalysis/ajaxadd",{pro_num:'<?php echo $this->project_data[0]['pro_num']?>',addproblem:addproblem,addsolve:addsolve},
                function(returnedData,status){
                    var result=returnedData;
                    if(result>0){
                        updatepage(1);
                        new PNotify({
                            title: '创建成功！',
                            text: "创建项目分析<?php echo $this->project_data[0]['pro_name']?>成功！",
                            type: 'success',
                            styling: 'bootstrap3'
                        });
                    }
                    else//网络错误
                    {alert("创建项目分析失败");}
                });
        }

        //刷新分页
        function updatepage(page){
            $.ajaxSetup({async: true});
            $.post("/project/proanalysis/ajaxpage",{query:'<?php echo $this->project_data[0]['pro_num']?>',page:page},
                function(returnedData,status){
                    var result=returnedData;
                    if(result!=null){
                        $('#pro_analysis_list').empty();
                        $('#pro_analysis_list').html(result);
                        init_DataTables();//必须重新初始化表，不然没有打印功能
                        $('[data-toggle="tooltip"]').tooltip({
                            container: 'body'
                        });
                    }
                    else//网络错误
                    {alert("失败");}
                });
        }
        //编辑
        function editanalysis(page,id)
        {
            alert('edit '+page+'_'+id)
        }
        //删除项目分析弹出框
        function deltanalysisalert(page,id) {
            $('#myModal1').modal('show');
            $('.modal-title').empty();
            $('.modal-title').html('删除确认');
            $('#content').empty();
            htmltext="<p>您确认要删除项目分析<?php echo $this->project_data[0]['pro_name']?>_"+id+"吗？</p>" +
                " <a type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">取消</a>" +
                " <a onclick=\"deltanalysis('<?php echo $this->project_data[0]['pro_num']?>','"+id+"')\" class=\"btn btn-danger\" data-dismiss=\"modal\">确定</a> ";
            $('#content').html(htmltext);
        }
        //删除项目分析
        function deltanalysis(pro_num,id) {
            $.ajaxSetup({async: true});
            $.post("/project/proanalysis/ajaxdelete",{pro_num:pro_num,id:id},
                function(returnedData,status){
                    var result=returnedData;
                    if(result>0){
                        updatepage(1);
                        new PNotify({
                            title: '删除成功！',
                            text: "删除项目分析<?php echo $this->project_data[0]['pro_name']?>_"+id+"成功！",
                            type: 'success',
                            nonblock: {
                                nonblock: true
                            },
                            styling: 'bootstrap3'
                        });
                    }
                    else//网络错误
                    {alert("删除项目分析失败");}
                });
        }

        $(function(){
            for(i in origin)
            {
                if($("#"+i).length>0){
                    $("#"+i).val(origin[i]);
                }else{
                    ;
                }
            }
            var date1=new Date($("#pro_startTime").val());
            var y1 = date1.getFullYear();
            var m1 = date1.getMonth() + 1;
            var date2=new Date($("#pro_endTime").val());
            var y2 = date2.getFullYear();
            var m2 = date2.getMonth() + 1;
            months= Math.abs((y2-y1)*12+m2-m1);
            $('#total_time').html(months);
        });
</script>

</html>